#!/usr/bin/env bash

# This script kills the 7-highlander process

# Find the PID of the 7-highlander process
PID=$(pgrep -f '7-highlander')

# Ensure the PID was found
if [ -z "$PID" ]; then
    echo "7-highlander process not found!"
    exit 1
fi

# Kill the 7-highlander process
kill $PID
echo "Killed"
